export const API_PATHS = {
    login : 'http://localhost:8000/api/auth/login',
    register : 'http://localhost:8000/api/auth/register',
    search : 'http://127.0.0.1:8000/api/home/search',
    uploadImagesPost : 'http://localhost:8000/api/home/images_post',
    createPost :'http://127.0.0.1:8000/api/home/create_post',
    getPostById : 'http://127.0.0.1:8000/api/home/get_posts',
    createComment : 'http://localhost:8000/api/home/create_comment',
    getAllComment :'http://localhost:8000/api/home/get_all_comment',
    getAllPostFriends : 'http://127.0.0.1:8000/api/home/get_posts_friends',
    getProfile : 'http://127.0.0.1:8000/api/profile',
    getProfileById :'http://localhost:8000/api/profile/user',
    getFriendsRequest: 'http://127.0.0.1:8000/api/home/friend_request',
    addPenddingFriend : 'http://localhost:8000/api/friends/add_pendding',
    deletePenddingFriend : 'http://localhost:8000/api/friends/delete_pendding',
    acceptAdd : 'http://localhost:8000/api/friends/add',
    cancelAdd : 'http://localhost:8000/api/friends/cancel',
    deleteFriend : 'http://localhost:8000/api/friends/delete',
    createRoom : 'http://localhost:8000/api/messages/create_room',
    sendMessage :'http://localhost:8000/api/messages/send_message',
    getAllRooms : 'http://127.0.0.1:8000/api/messages/get_rooms',
    getMessages : 'http://127.0.0.1:8000/api/messages/get_messages',
    deleteRooms : 'http://localhost:8000/api/messages/delete_room',
    deleteMessage : 'http://localhost:8000/api/messages/delete_message',
    getAllLike : 'http://localhost:8000/api/home/get_count_react',
    likeThisPost : 'http://localhost:8000/api/home/react_post',
    getNotices : 'http://127.0.0.1:8000/api/home/get_notifications',
    shareThisPost : 'http://localhost:8000/api/home/create_share',
}